# fly.toml app configuration file generated for gostream-frontend-autumn-leaf-6038 on 2025-05-03T01:40:39-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gostream-frontend"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
