# fly.toml app configuration file generated for gostream-subscription on 2025-05-06T00:53:13-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gostream-subscription'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 5002
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
