# fly.toml app configuration file generated for gostream-content on 2025-05-02T17:03:02-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gostream-content'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 5003
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "uploads"
  destination = "/app/uploads"
